export const Add_task="ADD_TASK"
export const Edit_task="EDIT_TASK"
export const Filter_task="Filter"
export const Filter_done="FILTER_DONE"
export const Filter_not_done="FILTER_NOT_DONE"
export const Reset="RESET"